working_directory: None

font:
  normal:
    family: 'JetBrains Mono'
  style: Regular
  size: 10

window:
  opacity: 0.8
  padding:
    x: 10

key_bindings:
  - {key: Right, mods: Alt, chars: "\x1BF"}
  - {key: Left, mods: Alt, chars: "\x1BB"}

colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Transparent cell backgrounds
  #
  # Whether or not `window.opacity` applies to all cell backgrounds or only to
  # the default background. When set to `true` all cells will be transparent
  # regardless of their background color.
  transparent_background_colors: true

  # Normal colors
  normal:
    black: '#000000'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#caa9fa'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#bfbfbf'

  # Bright colors
  bright:
    black: '#575b70'
    red: '#ff6e67'
    green: '#5af78e'
    yellow: '#f4f99d'
    blue: '#caa9fa'
    magenta: '#ff92d0'
    cyan: '#9aedfe'
    white: '#e6e6e6'
theme: Dracula
