#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='vim +Man!'
export MANWIDTH=999
export EDITOR='vim';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1;

# Speedy keys
xset r rate 350 40


# eval "$(fnm env)"
# eval "$(zoxide init zsh)"

export PATH
eval $(/opt/homebrew/bin/brew shellenv)

# Conda Setup
__conda_setup="$('/Users/jp/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jp/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/jp/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jp/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup


eval "`pip completion --zsh`"
